addons:
  sonarcloud:
    organization: "125philos"
    token:
      secure: "a6738bc3c71dc377a50ab80294777047f999d7d5" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar